[build]
  command = "yarn install --network-timeout 60000 && DISABLE_ESLINT_PLUGIN=true CI= yarn build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.0.0"
  YARN_VERSION = "1.22.22"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
